import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const items = ["do homework", "clean room", "buy food"];

export default function Home() {
  const [list, setList] = useState(items);
  const [item, setItem] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    setList((prevList) => [...prevList, item]);
    setItem("");
  };

  const handleChange = (e) => {
    setItem(e.target.value);
  };

  const removeItem = (idx) => {
    setList((prevList) => [
      ...prevList.slice(0, idx),
      ...prevList.slice(idx + 1),
    ]);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>To Do List</h1>
        <ul className={styles.list}>
          {list.map((el, idx) => (
            <li
              className={styles.item}
              key={idx}
              onClick={() => removeItem(idx)}
            >
              {el}
            </li>
          ))}
        </ul>

        <form className={styles.form} onSubmit={handleSubmit}>
          <input type="text" value={item} onChange={handleChange}></input>
          <input
            type="submit"
            className={styles.button}
            value="+ add item"
          ></input>
        </form>
      </main>
    </div>
  );
}
